# -*- coding: utf-8 -*-
"""P2HW2_PARNELTOM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4iHTb-Qu_NK34RG122BoiiGykUZ_yo5
"""

# THOMAS PARNELL
# 2/24//2025
# P2HW2
# ENTER GRADES FOLLOWING TEST

# Get 6 Grares from the user they should be floats
grade1 = float(input("Enter grade for Module 1: "))
grade2 = float(input("Enter grade for Module 2: "))
grade3 = float(input("Enter grade for Module 3: "))
grade4 = float(input("Enter grade for Module 4: "))
grade5 = float(input("Enter grade for Module 5: "))
grade6 = float(input("Enter grade for Module 6: "))

# create an empty list
grade_list = []

# use append method to add all grades into the list
# coe looks like this : list_name.append()(what_to_add-to _list)
grade_list.append(grade1)
grade_list.append(grade2)
grade_list.append(grade3)
grade_list.append(grade4)
grade_list.append(grade5)
grade_list.append(grade6)

# dispaly the list
print(grade_list)
print

# Display Value to user
print("-------------------Results----------------------------------------------")
print(f"{'Lowest Grade:': <20} {min(grade_list)}")
print(f"{'Highest Grade: ':<20} {max(grade_list)}")
print(f"{'Sum of Grade:': <20} {sum(grade_list)}")
Average =sum(grade_list)/len(grade_list)
print(f"{'Average:': <20} {Average:.2f}")
print("------------------------------------------------------------------------")